# run tests manually in the Actions-tab of the project
name: Trigger Tests Manually
on:
  workflow_dispatch:
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: mkdir reports
        - name: Run Robot Framework Tests
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image priviledges.
            path: ${{ github.workspace }}/reports
